Add Remove Operation
croct-tech/sdk-js pull request #115
Opened 2022-01-11 13:28 UTC by denis-rossati

## Summary

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (there's no hard-to-understand areas)
- [ ] I have made corresponding changes to the documentation (I'll do it in plug.js)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules (I'm not sure what this means)
- [x] I have checked my code and corrected any misspellings

2022-01-11 14:12 UTC, Fryuni commented
> Any dependent changes have been merged and published in downstream modules (I'm don't know how to be sure that this task is completed)
This check is to remind you to check that this PR does not depend on pending PRs from other repos. In this case it doesn't

Had you already opened the PR on the Plug to update the docs you should not check this box there yet since it depends on this PR here

😄

2022-01-11 14:27 UTC, amorimjuliana requested changes

2022-01-11 14:27 UTC, amorimjuliana commented on test/schemas/operationSchemas.test.ts
> +    ])('should remove value %s', (value: any) => {
The pattern here is to use `should allow value %s` for the test name.

2022-01-11 14:27 UTC, amorimjuliana commented on test/schemas/operationSchemas.test.ts
> +    test('should fail if value is invalid', () => {
And here, `should not allow value %s`.

2022-01-11 14:27 UTC, amorimjuliana commented on test/schemas/operationSchemas.test.ts
> +            removeOperation.validate({path: path, value: 'bar'});
To keep all tests standardized, please add the empty case on others as well, please.

2022-01-11 14:27 UTC, amorimjuliana commented on test/schemas/operationSchemas.test.ts
> +    test('should fail if value is invalid', () => {
Also, please rely on other tests examples for the invalid cases.

2022-01-11 21:00 UTC, amorimjuliana approved these changes

2022-01-12 13:48 UTC, marcospassos approved these changes

2022-01-12 13:49 UTC, marcospassos requested changes
Please add documentation for the new operation.

2022-01-12 13:49 UTC, merged