Adding linkOpened event
croct-tech/sdk-js pull request #116
Opened 2022-01-19 13:34 UTC by denis-rossati

## Summary

- The event requirements and types were added to `src/trackingEvents.ts`
- The event were added to the `src/schema/eventSchemas.ts` with one requirement: link. (I don't know if there is a more appropriate way to request a string in url format, but I based it on other occasions in the project)
- The event schema were added to the `src/facade/trackerFacade.ts`.

---

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas. `there is no hard-to-understand areas`
- [ ] I have made corresponding changes to the documentation. `I have to add the event to plug.js`
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules. `I have to add the event to plug.js`
- [x] I have checked my code and corrected any misspellings

---

2022-01-19 14:27 UTC, denis-rossati commented
I've initially updated the tslib to the version 2.3.1 because the typescript was complaining about the spread operator, and told that I should import a helper called `__spreadArrays`, [some posts](https://stackoverflow.com/questions/58329178/the-syntax-requires-an-imported-helper-named-spreadarrays) sugested that I should change the tslib to a new verison . But as I updated the version, the github automation complained back about the security check (as you can see in the commits above), so I changed the version to 2.2.0. 
Sorry

2022-01-20 21:55 UTC, amorimjuliana requested changes

2022-01-20 21:55 UTC, amorimjuliana commented on src/validation/stringType.ts
> +            new URL(value, 'http://any.thing');
Please add the comment below before this line:
`This simplistic approach covers the most common cases without inflating the library with an RFC 3986-compliant parser.`

2022-01-27 22:13 UTC, merged

2022-01-27 22:32 UTC, marcospassos commented
Great job! Completed in #120.